### ISSUE TITLE
startup error ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#1]
[6/7/2019, 12:49:06 PM] [SimpliSafe Client] TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (https.js:272:10)
    at Promise (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:224:30)
    at new Promise (<anonymous>)
    at API.request (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:223:12)
    at API.get_Sensors (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:157:33)
    at SimpliSafe.updateSensors (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:46:13)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:35:22)
    at ontimeout (timers.js:427:11)

Environment: MacOS 10.14.5  / Homebridge Version 0.4.45

**Comment by graanco** [comment]
Which version number on the package?

**Comment by graanco** [comment]
I fixed the issue for the cellular version of the system. The latest version should be 1.0.12

**Comment by murphmr** [comment]
Still getting this error with 1.0.14: Note the additional information in bold. 
[6/10/2019, 9:17:42 AM] Homebridge is running on port 51827.
(node:38618) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (https.js:272:10)
    at Promise (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:224:30)
    at new Promise (<anonymous>)
    at API.request (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:223:12)
    at API._authenticate (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:89:33)
    at API.login_via_credentials (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:69:16)
    at SimpliSafe.<anonymous> (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:30:12)
    at API.emit (events.js:182:13)
**(node:38618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:38618) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**Comment by graanco** [comment]
I just updated the code with some major changes... Try the newer one and try deleting the cache folder. verify the config.json file too. Next update I will set up a reset in the config.json for removal of the cache.

**Comment by murphmr** [comment]
Updated to the newer version - which cache do I need to delete? I removed cachedAccessories from the .homebridge/accessories directory.

**Comment by graanco** [comment]
Yes,  and I reran the code against my version 2 system and I discovered that the API gets flooded with a requests for updates. I think I got it.... I am going to update my patch in a little bit so look for ver 1.0.16.

**Comment by graanco** [comment]
I am sorry I missed this... clearing the cache accessories is to remove that folder... I will update the code for resetting the cache tomorrow.

**Comment by murphmr** [comment]
Ran homebridge in debug mode (DEBUG=* homebridge -D) after updating to 1.0.17: Not sure if this provides any additional information that is helpful - I removed all other accessories and platforms so that this would only have the simplisafeplaftorm information:
[6/11/2019, 8:36:31 AM] [SimpliSafe Client] Up and monitoring.
  EventedHTTPServer Server listening on port 51827 +0ms
[6/11/2019, 8:36:31 AM] Homebridge is running on port 51827.
(node:12609) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at ClientRequest.once (events.js:288:11)
    at new ClientRequest (_http_client.js:141:10)
    at Object.request (https.js:272:10)
    at Promise (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:248:34)
    at new Promise (<anonymous>)
    at webResponse (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:247:10)
    at API.apiconfig (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:71:22)
    at API.request (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:214:38)
    at API._authenticate (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:102:33)
    at API.login_via_credentials (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:82:16)
(node:12609) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12609) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  EventedHTTPServer [::ffff:192.168.1.89] New connection from client +870ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP server listening on port 61014 +1ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP request: /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:31] Client 9AA99204-435B-4591-81D5-4334C673507B verification complete +0ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP request: /accessories +1ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.89] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.95] New connection from client +80ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP server listening on port 61016 +0ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP request: /pair-verify +16ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:31] Client 9AA99204-435B-4591-81D5-4334C673507B verification complete +2ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.1.80] New connection from client +5ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP server listening on port 61018 +0ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP request: /accessories +1ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.95] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP request: /pair-verify +12ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:31] Client 9AA99204-435B-4591-81D5-4334C673507B verification complete +0ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP request: /accessories +5ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.80] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.1.129] New connection from client +222ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP server listening on port 61021 +0ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP request: /pair-verify +22ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:31] Client 9AA99204-435B-4591-81D5-4334C673507B verification complete +0ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP request: /accessories +4ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.129] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.74] New connection from client +6s
  EventedHTTPServer [::ffff:192.168.1.74] HTTP server listening on port 61026 +1ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP request: /pair-verify +6s
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:31] Client 258938CF-CE24-4383-959E-EDD0A96A88F3 verification complete +0ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP request: /accessories +7ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.74] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.169] New connection from client +3s
  EventedHTTPServer [::ffff:192.168.1.169] HTTP server listening on port 61029 +0ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP request: /pair-verify +20ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:31] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:31] Client 258938CF-CE24-4383-959E-EDD0A96A88F3 verification complete +1ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:31] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.169] HTTP Response is finished +1ms

**Comment by graanco** [comment]
Just out of curiosity you have the 24.99 plan and username and password setup correctly...

**Comment by murphmr** [comment]
SS3 with the 24.99 plan - I have been using chowielin/homebridge-simplisafe-security-system with no issues at all.

**Comment by murphmr** [comment]
So this specific issue appeared to be related to an outdated node.js version. Updated to v10.16.0 and the ERR_INVALID_ARG_TYPE is resolved. - New issue though - will open a new thread for that one.
